### ISSUE TITLE
Drift Detection: AWS::RDS::DBInstance postgresql: EngineVersion misdetects change from major to major.minor version

### ISSUE THREAD

**Issue by fknittel** [aws-cloudformation/cloudformation-coverage-roadmap#1003]
### Name of the resource

AWS::RDS::DBInstance

### Issue Description

Specifying only the major version (X) in field EngineVersion results in the drift detection detecting a manual change to the current major+minor version (X.Y), although no manual interaction with the service has occurred. Affects engine "postgres", see the [documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.DBVersions) regarding the major / minor version handling.

For MySQL the definition of major and minor version appears to be different (major is X.Y and minor is X.Y.Z), so this might need special-casing per engine.

### Expected Behavior

The actual value of the EngineVersion should be of the same specificity as the expected value.

### Observed Behavior

Drift for field `EngineVersion` from expected value `13` to actual value `13.3` detected.

### Test Cases

Example (expected) properties:
```json
{
  "AllocatedStorage": 5,
  "BackupRetentionPeriod": 7,
  "CopyTagsToSnapshot": true,
  "DBInstanceClass": "db.t3.small",
  "DBName": "survey",
  "DBSubnetGroupName": "XYZ",
  "DeletionProtection": false,
  "EnableCloudwatchLogsExports": [
    "upgrade",
    "postgresql"
  ],
  "Engine": "postgres",
  "EngineVersion": 13,
  "KmsKeyId": "arn:aws:kms:eu-central-1:XYZ",
  "MasterUsername": "XYZ",
  "Port": 5432,
  "PreferredBackupWindow": "01:00-02:00",
  "PubliclyAccessible": false,
  "StorageEncrypted": true,
  "StorageType": "gp2",
  "VPCSecurityGroups": [
    "XYZ"
  ]
}
```

**Comment by osdrv** [comment]
A fix for this issue was deployed. @fknittel could you please confirm the issue is resolved on your end?

**Comment by rgoltz** [comment]
@osdrv We also facing a Drift False-Positive regarding `EngineVersion` Drift False-Positive for RDS. Please note that this `AWS::RDS::DBInstance` is an Oracle RDS (DBEngineName = `oracle-se2` = **Oracle Standard Edition Two**). Please note that "Auto minor version upgrade" is set to "Yes".

After your update here in the issue, we -unfortunately- still see a Drift for EngineVersion in eu-central-1. Below the output of Drift Detection Detail View (Difference Summary)

| Property  | Change  | Expected value |  Current value |
| --------------- | --------------- | --------------- | --------------- |
| EngineVersion | NOT_EQUAL | 19.0.0.0.ru-2021-10.rur-2021-10.r1.* | 19.0.0.0.ru-2022-10.rur-2022-10.r1 |

![image](https://user-images.githubusercontent.com/16392819/219743252-82b42e4e-04fc-43f6-a059-d920f7fbe448.png)

Should PR https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/390 cover this case as well from your perspective? 

Just let me know, we could track this here as well or I should go head and open a new issue since it's not postgres as reported by @fknittel

**Comment by rgoltz** [comment]
PS: Since a "legacy stack", I not able to ensure that my example above is an out-of-band change, hence a real Drift. Input here is appreciated - I'm just aware of this page: https://docs.aws.amazon.com/AmazonRDS/latest/OracleReleaseNotes/oracle-version-19-0.html listing all EngineVersion for Oracle.

**Comment by osdrv** [comment]
@rgoltz thanks for checking. From the perspective of the change that has been landed, this drift detection case makes sense as CloudFormation engine tries to disambiguate the provided engine version and see if the observed value fits in the assumed range of versions. We might need to reassess this approach.

Could you please clarify: did this higher version (`19.0.0.0.ru-2022-10.rur-2022-10.r1`) come from an auto-upgrade?

**Comment by rgoltz** [comment]
> @rgoltz thanks for checking. From the perspective of the change that has been landed, this drift detection case makes sense as CloudFormation engine tries to disambiguate the provided engine version and see if the observed value fits in the assumed range of versions. We might need to reassess this approach.
> 
> Could you please clarify: did this higher version (`19.0.0.0.ru-2022-10.rur-2022-10.r1`) come from an auto-upgrade?

@osdrv Thank you very much for your input. We checked this RDS in more detail: The instance was patched to the latest Oracle-RU 19.0.0.0.ru-2022-10.rur-2022-10.r1 at the time due to the Auto-patching being enabled on the instance and happened during the weekly maintenance window. I had reviewed the API calls during the same time to confirm that it was not manually applied in the console. Based on this facts, you are right: It's a "real drift". We will fix this my proactively setting Oracle-Releases via CloudFormation. If we would miss this step, we getting a drift, which is a useful input for us. Other option is to modify the instance to disable auto minor version upgrade. Anyware, there is also an other issue #1309 ti discuss the interdependency between CFN Drift Detection and AutoMinorVersionUpgrade enabled.

It's great to see that the issue for postgres is fixed as confirmed from @fknittel - So, you will go ahead and resolve this case with reference to Oleg's fix, which is already deployed?
